package com.blog.blog.module;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.firstCategory
     *
     * @mbggenerated
     */
    private String firstCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.secondCategory
     *
     * @mbggenerated
     */
    private String secondCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.thirdCategory
     *
     * @mbggenerated
     */
    private String thirdCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.lastUpdateTime
     *
     * @mbggenerated
     */
    private String lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.createTime
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.editor
     *
     * @mbggenerated
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.firstCategory
     *
     * @return the value of blog.firstCategory
     *
     * @mbggenerated
     */
    public String getFirstCategory() {
        return firstCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.firstCategory
     *
     * @param firstCategory the value for blog.firstCategory
     *
     * @mbggenerated
     */
    public void setFirstCategory(String firstCategory) {
        this.firstCategory = firstCategory == null ? null : firstCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.secondCategory
     *
     * @return the value of blog.secondCategory
     *
     * @mbggenerated
     */
    public String getSecondCategory() {
        return secondCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.secondCategory
     *
     * @param secondCategory the value for blog.secondCategory
     *
     * @mbggenerated
     */
    public void setSecondCategory(String secondCategory) {
        this.secondCategory = secondCategory == null ? null : secondCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.thirdCategory
     *
     * @return the value of blog.thirdCategory
     *
     * @mbggenerated
     */
    public String getThirdCategory() {
        return thirdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.thirdCategory
     *
     * @param thirdCategory the value for blog.thirdCategory
     *
     * @mbggenerated
     */
    public void setThirdCategory(String thirdCategory) {
        this.thirdCategory = thirdCategory == null ? null : thirdCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.tag
     *
     * @return the value of blog.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.tag
     *
     * @param tag the value for blog.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.lastUpdateTime
     *
     * @return the value of blog.lastUpdateTime
     *
     * @mbggenerated
     */
    public String getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.lastUpdateTime
     *
     * @param lastUpdateTime the value for blog.lastUpdateTime
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime == null ? null : lastUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.createTime
     *
     * @return the value of blog.createTime
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.createTime
     *
     * @param createTime the value for blog.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.editor
     *
     * @return the value of blog.editor
     *
     * @mbggenerated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.editor
     *
     * @param editor the value for blog.editor
     *
     * @mbggenerated
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.creator
     *
     * @return the value of blog.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.creator
     *
     * @param creator the value for blog.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.version
     *
     * @return the value of blog.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.version
     *
     * @param version the value for blog.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}