package com.blog.blog.module;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.rightName
     *
     * @mbggenerated
     */
    private String rightName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.rightDescription
     *
     * @mbggenerated
     */
    private String rightDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.id
     *
     * @return the value of right.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.id
     *
     * @param id the value for right.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.rightName
     *
     * @return the value of right.rightName
     *
     * @mbggenerated
     */
    public String getRightName() {
        return rightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.rightName
     *
     * @param rightName the value for right.rightName
     *
     * @mbggenerated
     */
    public void setRightName(String rightName) {
        this.rightName = rightName == null ? null : rightName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.rightDescription
     *
     * @return the value of right.rightDescription
     *
     * @mbggenerated
     */
    public String getRightDescription() {
        return rightDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.rightDescription
     *
     * @param rightDescription the value for right.rightDescription
     *
     * @mbggenerated
     */
    public void setRightDescription(String rightDescription) {
        this.rightDescription = rightDescription == null ? null : rightDescription.trim();
    }
}