package com.blog.blog.module;

public class Right {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.rightName
     *
     * @mbggenerated
     */
    private String rightName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.rightDescription
     *
     * @mbggenerated
     */
    private String rightDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.lastUpdateTime
     *
     * @mbggenerated
     */
    private String lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.createTime
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.editor
     *
     * @mbggenerated
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.id
     *
     * @return the value of right.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.id
     *
     * @param id the value for right.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.rightName
     *
     * @return the value of right.rightName
     *
     * @mbggenerated
     */
    public String getRightName() {
        return rightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.rightName
     *
     * @param rightName the value for right.rightName
     *
     * @mbggenerated
     */
    public void setRightName(String rightName) {
        this.rightName = rightName == null ? null : rightName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.rightDescription
     *
     * @return the value of right.rightDescription
     *
     * @mbggenerated
     */
    public String getRightDescription() {
        return rightDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.rightDescription
     *
     * @param rightDescription the value for right.rightDescription
     *
     * @mbggenerated
     */
    public void setRightDescription(String rightDescription) {
        this.rightDescription = rightDescription == null ? null : rightDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.lastUpdateTime
     *
     * @return the value of right.lastUpdateTime
     *
     * @mbggenerated
     */
    public String getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.lastUpdateTime
     *
     * @param lastUpdateTime the value for right.lastUpdateTime
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime == null ? null : lastUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.createTime
     *
     * @return the value of right.createTime
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.createTime
     *
     * @param createTime the value for right.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.editor
     *
     * @return the value of right.editor
     *
     * @mbggenerated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.editor
     *
     * @param editor the value for right.editor
     *
     * @mbggenerated
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.creator
     *
     * @return the value of right.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.creator
     *
     * @param creator the value for right.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.version
     *
     * @return the value of right.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.version
     *
     * @param version the value for right.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}