package com.blog.blog.module;

public class RoleRightRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.roleId
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.rightId
     *
     * @mbggenerated
     */
    private Long rightId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.id
     *
     * @return the value of rolerightrelation.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.id
     *
     * @param id the value for rolerightrelation.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.roleId
     *
     * @return the value of rolerightrelation.roleId
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.roleId
     *
     * @param roleId the value for rolerightrelation.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.rightId
     *
     * @return the value of rolerightrelation.rightId
     *
     * @mbggenerated
     */
    public Long getRightId() {
        return rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.rightId
     *
     * @param rightId the value for rolerightrelation.rightId
     *
     * @mbggenerated
     */
    public void setRightId(Long rightId) {
        this.rightId = rightId;
    }
}