package com.blog.blog.module;

public class RoleRightRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.roleId
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.rightId
     *
     * @mbggenerated
     */
    private Long rightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.lastUpdateTime
     *
     * @mbggenerated
     */
    private String lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.createTime`
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.editor
     *
     * @mbggenerated
     */
    private String editor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolerightrelation.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.id
     *
     * @return the value of rolerightrelation.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.id
     *
     * @param id the value for rolerightrelation.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.roleId
     *
     * @return the value of rolerightrelation.roleId
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.roleId
     *
     * @param roleId the value for rolerightrelation.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.rightId
     *
     * @return the value of rolerightrelation.rightId
     *
     * @mbggenerated
     */
    public Long getRightId() {
        return rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.rightId
     *
     * @param rightId the value for rolerightrelation.rightId
     *
     * @mbggenerated
     */
    public void setRightId(Long rightId) {
        this.rightId = rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.lastUpdateTime
     *
     * @return the value of rolerightrelation.lastUpdateTime
     *
     * @mbggenerated
     */
    public String getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.lastUpdateTime
     *
     * @param lastUpdateTime the value for rolerightrelation.lastUpdateTime
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(String lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime == null ? null : lastUpdateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.createTime`
     *
     * @return the value of rolerightrelation.createTime`
     *
     * @mbggenerated
     */
    public String getCreateTim() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.createTime`
     *
     * @param createTime` the value for rolerightrelation.createTime`
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.editor
     *
     * @return the value of rolerightrelation.editor
     *
     * @mbggenerated
     */
    public String getEditor() {
        return editor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.editor
     *
     * @param editor the value for rolerightrelation.editor
     *
     * @mbggenerated
     */
    public void setEditor(String editor) {
        this.editor = editor == null ? null : editor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.creator
     *
     * @return the value of rolerightrelation.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.creator
     *
     * @param creator the value for rolerightrelation.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolerightrelation.version
     *
     * @return the value of rolerightrelation.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolerightrelation.version
     *
     * @param version the value for rolerightrelation.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}