spring:
  #resources:
    #static-locations: classpath:/templates/    将templates下作为静态资源可直接访问页面，但是会导致static内的内容找不到
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  thymeleaf:
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
    cache: false
mybatis:
  mapperLocations: classpath:mappers/*Mapper.xml
  typeAliasesPackage: com.blog.blog.module
pagehelper:
  helper-dialect: mysql
  #reasonable：分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询
  reasonable: true
  support-methods-arguments: true
