package com.blog.blog.mapper;

import com.blog.blog.module.RoleRightRelation;

public interface RoleRightRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int insert(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int insertSelective(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    RoleRightRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleRightRelation record);
}