package com.blog.blog.mapper;

import com.blog.blog.module.RoleRightRelation;
import com.blog.blog.module.RoleRightRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleRightRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int countByExample(RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int deleteByExample(RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int insert(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int insertSelective(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    List<RoleRightRelation> selectByExample(RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    RoleRightRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RoleRightRelation record, @Param("example") RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RoleRightRelation record, @Param("example") RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerightrelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleRightRelation record);
}