package com.blog.blog.mapper;

import com.blog.blog.module.UserRoleRelation;
import com.blog.blog.module.UserRoleRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int countByExample(UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int deleteByExample(UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int insert(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int insertSelective(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    List<UserRoleRelation> selectByExample(UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    UserRoleRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserRoleRelation record, @Param("example") UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserRoleRelation record, @Param("example") UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRoleRelation record);
}