package com.blog.blog.mapper;

import com.blog.blog.module.UserRoleRelation;

public interface UserRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int insert(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int insertSelective(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    UserRoleRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrolerelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRoleRelation record);
}